name: test
on: push

jobs:
  unit_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [2.4, 2.5]

    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1.63.0
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - run: bundle exec rake test:unit
